### PR TITLE
Added the ability for encoders with half steps.

### PR DESCRIPTION
**Pull request by dsiggi**
Hi,
I'm added the abilitya to use encoders with half steps.

Example:
```python
import time
from rotary_irq_esp import RotaryIRQ

r = RotaryIRQ(pin_num_clk=12, 
              pin_num_dt=13, 
              min_val=0, 
              max_val=5, 
              reverse=False, 
              range_mode=RotaryIRQ.RANGE_WRAP,
              half_step=True)

### CODE REVIEW

**Comment by miketeachman** [comment]
Hi Daniel,
Thanks for taking the time to make this pull request!   I don't own a 1/2 step encoder but I tested the PR and confirmed it doesn't change the existing behaviour of a full step encoder.  

I'd like to purchase a 1/2 step encoder.  Can you recommend one for me?

Regards,
Mike

**Comment by miketeachman** [comment]
Hi Daniel,
Thanks for taking the time to make this pull request!   I don't own a 1/2 step encoder but I tested the PR and confirmed it doesn't change the existing behaviour of a full step encoder.  

I'd like to purchase a 1/2 step encoder.  Can you recommend one for me?

Regards,
Mike

**Comment by dsiggi** [comment]
Hi,
I bought my encoders on ebay years ago. They are from Alps, but I don't know the part number.

Daniel

**Comment by miketeachman** [comment]
Thanks.  I'll check them out.

**Pull request merged**
